export const productList = [
   { name: " কক মুরগী(Live ) -[700gm]", price: 270 },
  { name: " বয়লার মুরগী [800gm] 4pes(c)", price: 270 },
   { name: "ফুল চিকেন(চামড়া সহ)", price: 280 },
  { name: "বেস্ট বনলেস", price: 410 },
  { name: "লেগ বনলেস", price: 380 },
  { name: "ফুল লেগ (চামড়া সহ)", price: 280 },
  { name: "ফুল লেগ (চামড়া ছাড়া)", price: 299 },
  { name: "থাই চামড়া সহ ", price: 325 },
  { name: "থাই চামড়া ছাড়া ", price: 350 },
  { name: "উইংস", price: 240 },
  { name: "শর্মা", price: 240 },
  { name: " বেস্ট বনলেস কিমা", price: 420 },
  { name: " বেস্ট বনলেস (চামড়া সহ) ", price: 420 },
  { name: " লেগ বনলেস কিমা", price: 420 },
  { name: "ডামিস্টিক(চামড়া সহ)", price: 299 },
  { name: "ডামিস্টিক(চামড়া ছাড়া)", price: 325 },
  { name: "লেয়ার মুরগি(লাল)", price: 419 },
  { name: "লেয়ার মুরগি(সাদা)", price: 419 },];